import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/toast-provider";
import { StudySessionProvider } from "@/providers/study-context-tracker-provider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Zen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark overflow-x-hidden">
      <body className={`${poppins.variable} antialiased overflow-x-hidden`}>
        <StudySessionProvider>{children}</StudySessionProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
